# Generated by Django 5.0 on 2024-02-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ttm_user_data',
            },
        ),
    ]
