# Generated by Django 5.0 on 2024-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='alogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausername', models.CharField(max_length=20)),
                ('apassword', models.CharField(max_length=20)),
            ],
        ),
    ]
