# Generated by Django 5.0 on 2024-01-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0003_alogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alogin',
            old_name='ausername',
            new_name='auser',
        ),
    ]
